name: Mend

on:
  push:
    branches:
      - main
      - release-*
      - dev-v2
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
    paths-ignore:
      - docs/**
  pull_request:
    branches:
      - main
      - release-*
      - dev-v2
    paths-ignore:
      - docs/**

concurrency:
  group: ${{ github.ref_name }}-mend
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  mend:
    if: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false) || (github.event_name == 'push' && github.event.repository.fork == false) }}
    uses: nginxinc/compliance-rules/.github/workflows/mend.yml@a27656f8f9a8748085b434ebe007f5b572709aad # v0.2
    secrets: inherit
    with:
      product_name: nginx-agent_${{ github.ref_name }}
      project_name: nginx-agent
